/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BulkUpload: typeof import('./src/components/shared/bulkupload/BulkUpload.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfirmationDialog: typeof import('./src/components/shared/ConfirmationDialog.vue')['default']
    DatePicker: typeof import('./src/components/shared/DatePicker.vue')['default']
    DateRangePicker: typeof import('./src/components/shared/DateRangePicker.vue')['default']
    DateTimePicker: typeof import('./src/components/shared/DateTimePicker.vue')['default']
    ECharts: typeof import('./src/components/ECharts/ECharts.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FileField: typeof import('./src/components/shared/FileField.vue')['default']
    InputField: typeof import('./src/components/shared/InputField.vue')['default']
    Instructions: typeof import('./src/components/shared/bulkupload/components/Instructions.vue')['default']
    Loader: typeof import('./src/components/shared/Loader.vue')['default']
    MenuBar: typeof import('./src/components/shared/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/shared/MenuItem.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    Pagination: typeof import('./src/components/shared/Pagination.vue')['default']
    RemoveRowButtonBulkUpload: typeof import('./src/components/shared/bulkupload/components/RemoveRowButtonBulkUpload.vue')['default']
    RichTextEditor: typeof import('./src/components/shared/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchButton: typeof import('./src/components/shared/SwitchButton.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TimePicker: typeof import('./src/components/shared/TimePicker.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
