# Generated by Django 5.2 on 2025-04-28 09:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated By')),
                ('name', models.CharField(max_length=255, verbose_name='Permission name')),
                ('module_name', models.CharField(max_length=255, verbose_name='Module name')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated By')),
                ('role_name', models.CharField(max_length=50, verbose_name='Role name')),
                ('is_system_generated', models.BooleanField(default=False)),
                ('profile_type', models.CharField(blank=True, choices=[('System Admin', 'System Admin'), ('Team Member', 'Team Member')], default='System Admin', max_length=20, null=True, verbose_name='Profile Type')),
                ('module_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this role.', related_name='roles', related_query_name='module_roles', to='core.modulepermissions', verbose_name='Module Permissions')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated By')),
                ('contact_number', models.CharField(blank=True, error_messages={'unique': 'User with this contact number already exists.'}, max_length=15, null=True, unique=True, verbose_name='User Contact Number')),
                ('phone_code', models.CharField(blank=True, default='966', max_length=5, null=True, verbose_name='Contact Number Country Code')),
                ('user_type', models.CharField(choices=[('Manager', 'Manager'), ('Team Member', 'Team Member'), ('System Admin', 'System Admin')], default='System Admin', max_length=12, verbose_name='User Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_users', to='core.role', verbose_name='User Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
